In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.naive_bayes import BernoulliNB, CategoricalNB, MultinomialNB, GaussianNB
from sklearn.preprocessing import LabelEncoder

# Gaussian Naive Bayes

In [2]:
# load iris dataset.

In [3]:
iris = load_iris(as_frame=True)

In [13]:
x = iris.data.to_numpy()
y = iris.target.to_numpy()

In [14]:
# this cell to glance the dataset
iris.frame.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [15]:
# declare Gaussian Naive Bayes model and fit it to the data.

GaussianNB()

In [17]:
# print the parameters of classifier

In [18]:
print(gaus_nb.theta_)

[[5.006 3.428 1.462 0.246]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]


In [19]:
# print the mean values of each class
print(np.mean(x[y == 0, :], axis=0))
print("=" * 50)
print(np.mean(x[y == 1, :], axis=0))
print("=" * 50)
print(np.mean(x[y == 2, :], axis=0))

[5.006 3.428 1.462 0.246]
[5.936 2.77  4.26  1.326]
[6.588 2.974 5.552 2.026]


In [20]:
print(gaus_nb.var_)

[[0.121764 0.140816 0.029556 0.010884]
 [0.261104 0.0965   0.2164   0.038324]
 [0.396256 0.101924 0.298496 0.073924]]


In [21]:
# print the variances of each class.
print(np.var(x[y == 0, :], axis=0))
print("=" * 50)
print(np.var(x[y == 1, :], axis=0))
print("=" * 50)
print(np.var(x[y == 2, :], axis=0))

[0.121764 0.140816 0.029556 0.010884]
[0.261104 0.0965   0.2164   0.038324]
[0.396256 0.101924 0.298496 0.073924]


# Bernoulli Naive Bayes

In [22]:
# to apply bernoulliNB, binarize the data x.
# each variable is transformed into 1 if the value is larger than its average and into 0 otherwise.

[5.84333333 3.05733333 3.758      1.19933333]


[[False  True False False]
 [False False False False]
 [False  True False False]
 [False  True False False]
 [False  True False False]]


In [25]:
# make true to 1 and false to 0.

In [ ]:
# print top 5 rows as an example

In [27]:
# declare Bernoulli naive bayes classifier and fit it to the binarized data.

BernoulliNB()

In [29]:
print(bern_nb.feature_log_prob_)

[[-3.95124372 -0.1900436  -3.95124372 -3.95124372]
 [-0.65540685 -1.75401914 -0.16705408 -0.23767165]
 [-0.14458123 -1.06087196 -0.01941809 -0.01941809]]


In [30]:
print(np.exp(bern_nb.feature_log_prob_))

[[0.01923077 0.82692308 0.01923077 0.01923077]
 [0.51923077 0.17307692 0.84615385 0.78846154]
 [0.86538462 0.34615385 0.98076923 0.98076923]]


In [31]:
print(np.exp(bern_nb.class_log_prior_))

[0.33333333 0.33333333 0.33333333]


# Categorical Naive Bayes

In [32]:
# load the dataset of categorical variables.

In [33]:
car = pd.read_csv('car.csv')
car.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [34]:
# divide independent variables x and dependent variable y.

In [35]:
x_car = car.drop("class", axis=1)
y_car = car["class"]

In [36]:
# transform string categories to integer.

In [37]:
# declare the LabelEncoder object.

In [38]:
# an example of how LabelEncoder works.
example_list = ["a", "c", "b", "a", "c"]

array([0, 2, 1, 0, 2])

In [ ]:
le.fit_transform()

In [39]:
# before applying label encoder, copy the data

In [40]:
x_car_encoded = 

In [41]:
# check if all variables are categorical
# (if some variables are already encoded as integer, those variables don't need to be encoded again.)

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
dtype: object


In [43]:
# apply label encoder for each variable.
n_sample, n_feature = 

label_encoder_list = 

for i in range(n_feature):
    

In [44]:
print(x_car_encoded)

     buying maint doors persons lug_boot safety
0         3     3     0       0        2      1
1         3     3     0       0        2      2
2         3     3     0       0        2      0
3         3     3     0       0        1      1
4         3     3     0       0        1      2
...     ...   ...   ...     ...      ...    ...
1723      1     1     3       2        1      2
1724      1     1     3       2        1      0
1725      1     1     3       2        0      1
1726      1     1     3       2        0      2
1727      1     1     3       2        0      0

[1728 rows x 6 columns]


In [45]:
# declare categorical naive bayes classifier and fit it to the data.

CategoricalNB(alpha=2)

In [47]:
# print unique target categories.

['acc' 'good' 'unacc' 'vgood']


In [48]:
# count the number of samples in each class

In [ ]:
unique_y, count_y = 

In [49]:
# the ratio of each class

[0.22222222 0.03993056 0.70023148 0.03761574]


In [50]:
# the same values in categorical naive bayes

[0.22222222 0.03993056 0.70023148 0.03761574]


In [ ]:
print(np.exp(cat_nb.class_log_prior_))

In [51]:
print(cat_nb.feature_log_prob_)

[array([[-1.27078147, -1.46040233, -1.2090879 , -1.66719675],
       [-3.65065824, -0.47260441, -1.1249296 , -3.65065824],
       [-1.31806807, -1.54428382, -1.50654349, -1.21332124],
       [-3.59731226, -0.57688737, -0.95825493, -3.59731226]]), array([[-1.29843301, -1.42796706, -1.2090879 , -1.66719675],
       [-3.65065824, -0.47260441, -1.1249296 , -3.65065824],
       [-1.34922323, -1.50654349, -1.50654349, -1.21332124],
       [-1.58240924, -0.95825493, -0.95825493, -3.59731226]]), array([[-1.55242123, -1.35614132, -1.32687094, -1.32687094],
       [-1.51059208, -1.34807315, -1.34807315, -1.34807315],
       [-1.31195184, -1.39453843, -1.42138568, -1.42138568],
       [-1.80555279, -1.4572461 , -1.19941699, -1.19941699]]), array([[-5.27299956, -0.66782937, -0.72970478],
       [-3.62434093, -0.67990195, -0.76214005],
       [-0.74374819, -1.35392908, -1.32257855],
       [-3.5695327 , -0.79694397, -0.65176196]]), array([[-0.98254012, -1.04616581, -1.2933179 ],
       [-1.05939158

In [52]:
x_column_names = list(car.columns[:-1])
print(x_column_names)

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']


In [53]:
for i, column in enumerate(x_column_names):
    print(f"{column:<10}", len(np.unique(x_car_enc.iloc[:, i])))

buying     4
maint      4
doors      4
persons    3
lug_boot   3
safety     3


In [54]:
print(np.exp(cat_nb.feature_log_prob_[0]))

[[0.28061224 0.23214286 0.29846939 0.18877551]
 [0.02597403 0.62337662 0.32467532 0.02597403]
 [0.26765189 0.2134647  0.22167488 0.29720854]
 [0.02739726 0.56164384 0.38356164 0.02739726]]


In [55]:
print(np.exp(cat_nb.feature_log_prob_[0]).sum(1))

[1. 1. 1. 1.]


In [56]:
print(np.exp(cat_nb.feature_log_prob_[3]))

[[0.00512821 0.51282051 0.48205128]
 [0.02666667 0.50666667 0.46666667]
 [0.47532895 0.25822368 0.26644737]
 [0.02816901 0.45070423 0.52112676]]


In [57]:
print(np.exp(cat_nb.feature_log_prob_[3]).sum(1))

[1. 1. 1. 1.]


In [58]:
# make predictions (and calculate predicted probabilities)

In [59]:
y_car_pred = 

In [60]:
y_car_prob = 

In [61]:
# compute the accuracy.

0.8674768518518519


# Multinomial Naive Bayes

In [63]:
# load spam dataset.

In [64]:
spam = pd.read_csv("spam.csv")
spam.head()

alreadi  also  alway  amp  anyth  around  ask  award  babe  back  ...  \
0        0     0      0    0      0       0    0      0     0     0  ...   
1        0     0      0    0      0       0    0      0     0     0  ...   
2        0     0      0    0      0       0    0      0     0     0  ...   
3        1     0      0    0      0       0    0      0     0     0  ...   
4        0     0      0    0      0       1    0      0     0     0  ...   

   wish  word  work  would  www  ya  ye  yeah  year  target  
0     0     0     0      0    0   0   0     0     0       0  
1     0     0     0      0    0   0   0     0     0       0  
2     0     0     0      0    0   0   0     0     0       1  
3     0     0     0      0    0   0   0     0     0       0  
4     0     0     0      0    0   0   0     0     0       0  

[5 rows x 176 columns]

In [65]:
n_sample, n_feature = 
print(n_sample)
print(n_feature)

5108
176


In [66]:
x = spam.drop("target", axis=1)
y = spam["target"]

In [67]:
unique_y, count_y = 

[(0, 4366), (1, 742)]


In [ ]:
# print the number of samples for each class

In [68]:
# declare multinomial naive bayes and fit it to the data.

In [69]:
multi_nb = 

MultinomialNB(alpha=1)

In [70]:
print(np.exp(multi_nb.class_log_prior_))

[0.85473767 0.14526233]


In [71]:
print(np.exp(multi_nb.feature_log_prob_).shape)

(2, 175)


In [72]:
print(np.exp(multi_nb.feature_log_prob_)[0])

[5.63014292e-03 4.45461857e-03 3.65031244e-03 5.50640351e-03
 4.76396709e-03 3.71218214e-03 7.91932191e-03 1.23739405e-04
 4.70209738e-03 8.10493102e-03 3.71218214e-04 4.45461857e-03
 1.86227804e-02 3.89779125e-03 5.13518530e-03 8.66175834e-04
 9.89915239e-04 3.27909423e-03 6.18697024e-05 4.88770649e-03
 6.18697024e-04 1.11365464e-03 1.86227804e-02 9.28045536e-04
 3.34096393e-03 7.42436429e-04 9.40419477e-03 1.55911650e-02
 6.80566726e-03 8.53801893e-03 3.46470333e-03 2.72226691e-03
 5.44453381e-03 2.53665780e-03 5.81575203e-03 3.27909423e-03
 3.27909423e-03 4.20713976e-03 3.58844274e-03 3.77405185e-03
 5.69201262e-03 2.28299202e-02 6.80566726e-03 2.63564932e-02
 3.65031244e-03 1.46631195e-02 1.45393801e-02 6.55818846e-03
 1.97364351e-02 6.18697024e-05 4.20713976e-03 3.58844274e-03
 3.15535482e-03 7.48623399e-03 2.47478810e-03 6.68192786e-03
 7.60997340e-03 1.02703706e-02 8.10493102e-03 2.90787601e-03
 5.07331560e-03 4.51648828e-03 1.54674256e-02 4.14527006e-03
 3.77405185e-03 8.414279

In [73]:
print(np.exp(multi_nb.feature_log_prob_)[0].sum())

1.0000000000000004
